apply plugin: 'maven-publish'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}



afterEvaluate {
    publishing {
        publications {
            // Creates a publication named "release". You can give it any name.
            release(MavenPublication) {
                // Set the Maven coordinates for your library
                groupId = 'com.github.maribeiroleya' // e.g., com.github.yourusername
                artifactId = 'leya-android-pdf-viewer'
            }
        }
    }
}