apply plugin: 'com.android.application'

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.pdfviewer"
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 3
        versionName "3.0.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            debuggable true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    namespace 'com.github.barteksc.sample'
}

dependencies {
    implementation project(':android-pdf-viewer')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.code.gson:gson:2.13.2'
}
